export const GET_BIKELIST_SUCCESS = 'bike_list/GET_BIKELIST_SUCCESS';
export const GET_BIKELIST_ERROR = 'bike_list/GET_BIKELIST_ERROR';
export const POST_BIKELIST_SUCCESS = 'bike_list/POST_BIKELIST_SUCCESS';
export const POST_BIKELIST_ERROR = 'bike_list/POST_BIKELIST_ERROR';
export const DELETE_BIKELIST_SUCCESS = 'bike_list/DELETE_BIKELIST_SUCCESS';
export const DELETE_BIKELIST_ERROR = 'bike_list/DELETE_BIKELIST_ERROR';
export const PATCH_BIKELIST_SUCCESS = 'bike_list/PATCH_BIKELIST_SUCCESS';
export const PATCH_BIKELIST_ERROR = 'bike_list/PATCH_BIKELIST_ERROR';
